site_name: SirEdvin's Mods
theme:
  name: material
  palette: 
    scheme: slate
  
nav:
  - 'Home': index.md
  - 'Turtlematic':
    - 'Home': turtlematic/index.md
    - 'APIs':
      - 'Turtlematic APIs': turtlematic/api/introduction.md
      - 'Configuration API': turtlematic/api/configuration.md
      - 'Operation API': turtlematic/api/operation.md
      - 'Fuel API': turtlematic/api/fuel.md
      - 'Look API': turtlematic/api/look.md
      - 'Interaction API': turtlematic/api/interaction.md
      - 'Capture API': turtlematic/api/capture.md
      - 'Scan API': turtlematic/api/scan.md
      - 'Warp API': turtlematic/api/warp.md
      - 'Experience API': turtlematic/api/experience.md
    - "Automata":
      - "Base automata": turtlematic/automata/automata.md
      - "End automata": turtlematic/automata/end.md
      - "Husbandry automata": turtlematic/automata/husbandry.md
      - "Mason automata": turtlematic/automata/mason.md
      - "Smithing automata": turtlematic/automata/smithing.md
      - "Brewing automata": turtlematic/automata/brewing.md
      - "Enchanting automata": turtlematic/automata/enchanting.md
    - "Miscellaneous":
      - "Turtle chatter": turtlematic/miscellaneous/turtle_chatter.md
      - "Creative chest": turtlematic/miscellaneous/creative_chest.md
      - "Soul scrapper": turtlematic/miscellaneous/soul_scrapper.md
      - "Piston turtle": turtlematic/miscellaneous/piston_turtle.md
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
